## path
# data_path: ../data/ende/test_small.jsonl
memory_path: null
# output_path: ../data/ende/test_small_hyp.txt
memory_encoding: concate
pretrained_model_path: null
src: src
trg: trg
## training
per_device_eval_batch_size: 32
accelerator: gpu
train_max_src_len: 250
train_max_trg_len: 130
seed: 980406
## generation
gen_max_len: 118
gen_min_len: 3
num_beams: 10
num_return_sequences: 10

num_beam_groups: 10
early_stopping: true
length_penalty: 1
